"""Figure 2: the real open Bloch trajectory for one selected round."""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt

from bloch_utils import draw_bloch_sphere, set_bloch_axes
from model import SimulationConfig, simulate_five_rounds
from psb_utils import open_path_geometric_phase


SELECTED_ROUND = 3


def main() -> None:
    config = SimulationConfig()
    item = simulate_five_rounds(config)[SELECTED_ROUND - 1]

    path = item["bloch"]
    states = item["states"]
    times = item["times"]
    lambda_k = float(item["lambda"])

    gamma = open_path_geometric_phase(times, states, lambda_k, config)

    figure = plt.figure(figsize=(9.0, 8.0), facecolor="none")
    axis = figure.add_subplot(111, projection="3d", facecolor="none")
    figure.patch.set_facecolor("none")
    axis.set_facecolor("none")

    draw_bloch_sphere(axis)

    line = axis.plot(
        path[:, 0],
        path[:, 1],
        path[:, 2],
        linewidth=2.5,
        label=rf"Real path generated by $H(\lambda_{SELECTED_ROUND})$",
    )[0]
    colour = line.get_color()

    start = path[0]
    end = path[-1]

    axis.scatter(
        start[0],
        start[1],
        start[2],
        s=70,
        color=colour,
        depthshade=False,
    )
    axis.scatter(
        end[0],
        end[1],
        end[2],
        s=70,
        color=colour,
        depthshade=False,
    )
    axis.text(
        1.07 * start[0],
        1.07 * start[1],
        1.07 * start[2],
        r"$A$",
        color=colour,
    )
    axis.text(
        1.07 * end[0],
        1.07 * end[1],
        1.07 * end[2],
        r"$B$",
        color=colour,
    )

    # set_bloch_axes(
    #     axis,
    #     rf"Open PSB path — round {SELECTED_ROUND}, "
    #     rf"$\lambda_{SELECTED_ROUND}={lambda_k:.3f}$",
    # )
    axis.legend(
        title=rf"$\gamma_{{\rm SB}}={gamma:.4f}\ {{\rm rad}}$",
        loc="upper left",
        bbox_to_anchor=(0.01, 0.98),
    )
    figure.tight_layout()

    output = Path(__file__).parent / "figures" / "02_psb_open_path.svg"
    figure.savefig(output, bbox_inches="tight", transparent=True)
    print(f"Saved: {output}")
    print(f"Gauge-invariant open-path phase: {gamma:.10f} rad")


if __name__ == "__main__":
    main()
